#!/bin/sh

#Set several variables.
echo "Please input your region. [us|eu]"
read REGION
URL="ws-$REGION.herokuapp.com"
LPORT="1088"
PASSWORD="qbasic"
CIPHER="aes-256-cfb"
RPORT="80"
LHOST="0.0.0.0"

node local.js -s $URL -l $LPORT -m $CIPHER -k $PASSWORD -r $RPORT -b $LHOST

